// bwm-react-new/src/pages/RentalDetail.js
import React from 'react';

class RentalDetail extends React.Component {

  render() {
    return (
      <section id="rentalDetails">
        <div className="upper-section">
          <div className="row">
            <div className="col-md-6">
              {/* <!-- TODO: Display rental image --> */}
              <img src="#" alt="" />
            </div>
            <div className="col-md-6">
              {/* <!-- TODO: Display rental image --> */}
              <img src="#" alt="" />
            </div>
          </div>
        </div>

        <div className="details-section">
          <div className="row">
            <div className="col-md-8">
              <div className="rental">
                {/* <!-- TODO: Display shared category --> */}
                <h2 className="rental-type">true house</h2>
                {/* <!-- TODO: Display title --> */}
                <h1 className="rental-title">Some Title</h1>
                {/* <!-- TODO: Display city --> */}
                <h2 className="rental-city">New York</h2>
                <div className="rental-room-info">
                  {/* <!-- TODO: Display numOfRooms --> */}
                  <span><i className="fa fa-building"></i>4 bedrooms</span>
                    {/* // <!-- TODO: Display numOfRooms + 4 --> */}
                  <span><i className="fa fa-user"></i> 8 guests</span>
                  {/* // <!-- TODO: Display numOfRooms + 2 --> */}
                  <span><i className="fa fa-bed"></i> 6 beds</span>
                </div>
                {/* <!-- TODO: Display description --> */}
                <p className="rental-description">
                  Some Description
                </p>
                <hr/>
                <div className="rental-assets">
                  <h3 className="title">Assets</h3>
                  <div className="row">
                    <div className="col-md-6">
                      <span><i className="fa fa-asterisk"></i> Cooling</span>
                      <span><i className="fa fa-thermometer"></i> Heating</span>
                      <span><i className="fa fa-location-arrow"></i> Iron</span>
                    </div>
                    <div className="col-md-6">
                      <span><i className="fa fa-desktop"></i> Working area</span>
                      <span><i className="fa fa-cube"></i> Washing machine</span>
                      <span><i className="fa fa-cube"></i> Dishwasher</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-md-4"> BOOKING</div>
          </div>
        </div>
      </section> 
    )
  }
}

export default RentalDetail;

// bwm-new/src/app/rental/rental-detail/rental-detail.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'bwm-rental-detail',
  templateUrl: './rental-detail.component.html'
})
export class RentalDetailComponent {

  public rentalId = '';

  // dependency injection
  constructor(private route: ActivatedRoute) {}

  ngOnInit() {
    this.route.params.subscribe(params => {
      this.rentalId = params['rentalId']
    })
  }
}
<section *ngIf="rental && rental._id" id="rentalDetails">
  <div class="upper-section">
    <div class="row">
      <div class="col-md-6">
        <!-- TODO: Display rental image -->
        <img [src]="rental.image" alt="" />
      </div>
      <div class="col-md-6">
        <!-- TODO: Display rental image -->
        <img [src]="rental.image" alt="" />
      </div>
    </div>
  </div>

  <div class="details-section">
    <div class="row">
      <div class="col-md-8">
        <div class="rental">
          <!-- TODO: Display shared category -->
          <h2 class="rental-type type-{{ rental.category }}">
            {{ rental.shared ? "Shared" : "Whole" }} {{ rental.category }}
          </h2>
          <!-- TODO: Display title -->
          <h1 class="rental-title">{{ rental.title }}</h1>
          <!-- TODO: Display city -->
          <h2 class="rental-city">{{ rental.city }}</h2>
          <div class="rental-room-info">
            <!-- TODO: Display numOfRooms -->
            <span
              ><i class="fa fa-building"></i
              >{{ rental.numOfRooms }} bedrooms</span
            >
            <!-- TODO: Display numOfRooms + 4 -->
            <span
              ><i class="fa fa-user"></i
              >{{ rental.numOfRooms + 4 }} guests</span
            >
            <!-- TODO: Display numOfRooms + 2 -->
            <span
              ><i class="fa fa-bed"></i>{{ rental.numOfRooms + 2 }} beds</span
            >
          </div>
          <!-- TODO: Display description -->
          <p class="rental-description">
            {{ rental.description }}
          </p>
          <hr />
          <div class="rental-assets">
            <h3 class="title">Assets</h3>
            <div class="row">
              <div class="col-md-6">
                <span><i class="fa fa-asterisk"></i> Cooling</span>
                <span><i class="fa fa-thermometer"></i> Heating</span>
                <span><i class="fa fa-location-arrow"></i> Iron</span>
              </div>
              <div class="col-md-6">
                <span><i class="fa fa-desktop"></i> Working area</span>
                <span><i class="fa fa-cube"></i> Washing machine</span>
                <span><i class="fa fa-cube"></i> Dishwasher</span>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">BOOKING</div>
    </div>
  </div>
</section>
