// bwm-new/src/app/shared/rental-card/rental-card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'bwm-rental-card',
  templateUrl: './rental-card.component.html',
  styleUrls: ['./rental-card.component.scss']
})
export class RentalCardComponent {

  @Input('rental') rental: any;
}

<a href="#">
    <div class="card bwm-card">
      <img class="card-img-top" src="http://via.placeholder.com/350x250" alt="">
      <div class="card-block">
        <h6 class="card-subtitle">Whole {{rental.category}} &#183; {{rental.city}}</h6>
        <h4 class="card-title">{{rental.title}}</h4>
        <p class="card-text">${{rental.dailyPrice}} per Night &#183; Free Cancelation</p>
      </div>
    </div>
  </a>

// bwm-react-new/src/components/rental/RentalCard.js
import React from 'react';

const RentalCard = ({rental}) => {

  return (
    <div className="card bwm-card">
      <img 
        className="card-img-top" 
        src={rental.image}
        alt={rental.title} />
      <div className="card-body">
        <h6 className={`card-subtitle mb-0 type-${rental.category}`}>
          {rental.shared ? 'Shared' : 'Whole'} {rental.category} &#183; {rental.city}
        </h6>
        <h5 className="card-title big-font">{rental.title}</h5>
        <p className="card-text">${rental.dailyPrice} per Night &#183; Free Cancelation</p>
      </div>
    </div>
  )
}

export default RentalCard;
